#!/usr/bin/env ruby

# frozen_string_literal: true

require 'rubygems'
require 'bundler/setup'

require 'rbczmq'
require 'pry-byebug'

# Think of REQ and DEALER sockets as "clients" and REP and ROUTER sockets as
# "servers". Mostly, you'll want to bind REP and ROUTER sockets, and connect
# REQ and DEALER sockets to them. It's not always going to be this simple, but
# it is a clean and memorable place to start.

@context = ZMQ::Context.new

WILHELM_PORT = '5557'
WALTER_PORT = '5556'

def publisher
  @context.bind(:PUB, "tcp://*:#{WILHELM_PORT}")
end

def listen(context = @context)
  Thread.new(context) do |ctx|
    subscriber = ctx.connect(:SUB, "tcp://localhost:#{WALTER_PORT}")
    subscriber.subscribe('')
    begin
      received = 0
      while received < 10 do
        puts subscriber.recv
        received += 1
      end
    rescue StandardError => e
      puts "error! #{e}"
    end
    puts 'thread ending...'
  end
end

talk = publisher

binding.pry

@context.destroy
